In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

import matplotlib.pyplot as plt
%matplotlib inline

import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [2]:
from sklearn.feature_extraction import DictVectorizer

In [5]:
v =DictVectorizer(sparse=False)
D = [{'A' : 1, 'B' : 2}, {'B' : 3, 'C' : 1}]
X =v.fit_transform(D)
X

array([[1., 2., 0.],
       [0., 3., 1.]])

In [6]:
v.feature_names_

['A', 'B', 'C']

In [7]:
F = [{'A' : 1, 'B' : 2}, {'D' : 3, 'C' : 1}]
X1 =v.fit_transform(F)
X1

array([[1., 2., 0., 0.],
       [0., 0., 1., 3.]])

In [8]:
v.feature_names_

['A', 'B', 'C', 'D']

In [9]:
v.transform({'C': 3, 'F':2})

array([[0., 0., 3., 0.]])

In [10]:
v.fit_transform({'C': 3, 'F':2})

array([[3., 2.]])

In [11]:
v.feature_names_

['C', 'F']

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',      
]

vect = CountVectorizer()
vect.fit(corpus)
vect.vocabulary_

CountVectorizer()

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [16]:
vect.transform(['This is the second document.']).toarray()

array([[0, 1, 0, 1, 0, 0, 1, 1, 0, 1]], dtype=int64)

In [15]:
vect.transform(['Something completely new.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [17]:
vect.transform(corpus).toarray()

array([[0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 0, 2, 1, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0]], dtype=int64)

In [22]:
vect = CountVectorizer(stop_words=["and","is","the","this"]).fit(corpus)
vect.vocabulary_

{'first': 1, 'document': 0, 'second': 4, 'third': 5, 'one': 3, 'last': 2}

In [23]:
vect = CountVectorizer(stop_words="english").fit(corpus)
vect.vocabulary_

{'document': 0, 'second': 1}